Neel/updating page styles for mobile
uwblueprint/social-diversity-for-children pull request #128
Opened 2021-11-07 23:44 UTC by neelismail01

### Notion ticket link

[Start Mobile Responsive Designs for static pages](https://www.notion.so/uwblueprintexecs/Start-Mobile-Responsive-Designs-for-static-pages-71b40c3d94f1448ab3fde0ca1d376fb8)

### Implementation description

- Implemented the useBreakPointValue hook to determine device type and added logic to various components appropriately style based on the recognized device type

### Steps to test

1. Right click on the webpage in the Chrome web browser, and click "Inspect"
2. Change the device type to mobile in the device toolbar
3. Verify that the webpages match the Figma designs when in the mobile view

### What should reviewers focus on?

- Ensure that the webpages match the Figma designs

### Checklist

-   [ ] My PR name is descriptive and in imperative tense
-   [ ] I have run the linter
-   [ ] I have requested a review from the PL, and/or other devs who have background knowledge on this PR or who will be building on top of this PR

2021-11-17 04:36 UTC, MatoPlus requested changes
Looks really good! I caught some small things we can change.

2021-11-17 04:36 UTC, MatoPlus commented on pages/login.tsx
>                      <FormControl id="email">
I think some of the text should be center-aligned: 


For line 52
```typescript
                        <Text
                            fontWeight="400"
                            fontSize="16px"
                            mt="20px"
                            textAlign="center"
                        >
                            Registration for Summer 2021 classes begin June 31,
                            2021
                        </Text>
```

![image](https://user-images.githubusercontent.com/44826218/142134397-73ce42bb-b438-4362-928b-7a4e1ef11132.png)

2021-11-17 04:36 UTC, MatoPlus commented on pages/login.tsx
>                          >
```suggestion
                            color="brand.300"
                            textAlign="center"
                        >
```

2021-11-17 04:36 UTC, MatoPlus commented on src/components/WelcomeToSDC.tsx
>                                  )}
For the button, please add a breakpoint for width on line 60, (change on line 70)

```typescript
                                        <Button
                                            color="white"
                                            backgroundColor={
                                                colourTheme.colors.Blue
                                            }
                                            _hover={{
                                                backgroundColor:
                                                    colourTheme.colors
                                                        .LightBlue,
                                            }}
                                            width={{ base: "100%", md: "50%" }}
                                            borderRadius="6px"
                                            fontWeight={"200"}
                                        >
                                            {t("home.registerNow")}
                                        </Button>
```

![image](https://user-images.githubusercontent.com/44826218/142134639-aa51d0d6-d86f-4aac-8cf4-67212c9bf48c.png)

2021-11-17 04:36 UTC, MatoPlus commented on src/components/WelcomeToSDC.tsx
> +    const variant = useBreakpointValue({ base: "mobile", lg: "computer" });
you got the idea here but can we maybe use a boolean, this seems difficult to keep track of
```suggestion
    const isMobileLayout = useBreakpointValue({ base: true, lg: false });
```

2021-11-17 04:36 UTC, MatoPlus commented on src/components/WelcomeToSDC.tsx
> +                        <Box w={variant === "computer" ? "50%" : "100%"}>
do we need a break point here?

2021-11-17 04:36 UTC, MatoPlus commented on src/components/WelcomeToSDC.tsx
> +                        <Box w={variant === "computer" ? "50%" : "100%"}>
do we need to use the breakpoint state here?

2021-11-17 04:36 UTC, MatoPlus commented on src/components/Navbar.tsx
> +    const variant = useBreakpointValue({ base: "sidebar", lg: "navbar" });
let's stick with booleans:
```suggestion
    const isSideBar = useBreakpointValue({ base: true, lg: false });
```

2021-11-23 00:53 UTC, bekahma approved these changes

2021-11-27 17:13 UTC, merged