Bug fix: change descriptions for some success messages
uwblueprint/social-diversity-for-children pull request #129
Opened 2021-11-08 01:00 UTC by LenaNguyen

Adding a participant successfully:
This is a suggestion for changing the message. It looks funny with the number of times it says participant and successfully.
![image](https://user-images.githubusercontent.com/43686735/140669180-a020c830-9166-4b10-bc76-763ef44f33a8.png)

Successfully registering for a class:
This was grammatically incorrect.

### Checklist

-   [x] My PR name is descriptive and in imperative tense
-   [x] I have run the linter
-   [x] I have requested a review from the PL, and/or other devs who have background knowledge on this PR or who will be building on top of this PR

2021-11-08 02:20 UTC, MatoPlus commented
I think we originally had this in our design:
![image](https://user-images.githubusercontent.com/44826218/140674155-0656458b-162a-481a-b2a2-1a443bfbb90c.png)

@LenaNguyen Do you mind tackling this? Otherwise, lmk and I'll make a ticket to take a look on a later date!

2021-11-08 07:29 UTC, LenaNguyen commented
> I think we originally had this in our design: ![image](https://user-images.githubusercontent.com/44826218/140674155-0656458b-162a-481a-b2a2-1a443bfbb90c.png)
> 
> @LenaNguyen Do you mind tackling this? Otherwise, lmk and I'll make a ticket to take a look on a later date! I think it's just passing participant name states around.

updated! 
![image](https://user-images.githubusercontent.com/43686735/140700953-e3559bb6-abc8-4871-b8b0-eee93d4bf8ed.png)

2021-11-08 13:53 UTC, MatoPlus requested changes
One last little thing and I think it's good to merge!

2021-11-08 13:53 UTC, MatoPlus commented on src/components/parent-form/ParticipantCreatedPage.tsx
> +                                </div>
We want to minimize the amount of non-chakra components, especially div.
```suggestion
                                    <strong>{name}</strong> has been
                                    successfully added as a participant in your
                                    account!
```

^ if that doesn't work, maybe just use empty tags instead, "<>"

2021-11-14 21:18 UTC, MatoPlus approved these changes
LGTM!

2021-11-14 21:18 UTC, merged