Implement get program endpoint
uwblueprint/social-diversity-for-children pull request #20
Opened 2021-06-27 02:50 UTC by brandonwong368

### Notion ticket link

[Ticket Name](https://www.notion.so/uwblueprintexecs/086c1b564dbf478faa649a8880e34b81?v=9d3f8002a0d1477ba395616dfc082af7&p=eb4f61da390f40b98d2321e90a5b3126)

### Implementation description

-add `getProgram` and `getPrograms` functions as part of the GET program endpoints

### Steps to test

1.

### What should reviewers focus on?

-

### Checklist

-   [ ] My PR name is descriptive and in imperative tense
-   [ ] I have run the linter
-   [ ] I have requested a review from the PL, and/or other devs who have background knowledge on this PR or who will be building on top of this PR

2021-06-27 17:50 UTC, feng-eric commented on pages/api/program/index.ts
> +            res.status(200).json({});
```suggestion
    
```

2021-06-27 17:50 UTC, feng-eric commented on pages/api/program/index.ts
> +            res.status(200).json({});
Remove this line as it is being done in `returnOK`

2021-06-27 17:50 UTC, feng-eric commented on pages/api/program/index.ts
> +            // TODO: add JSON response for method not allowed
Remove TODO

2021-06-27 17:51 UTC, feng-eric commented on services/database/program.ts
> +        //get program() exposes CRUD operations for Program model
Remove comments

2021-06-27 17:51 UTC, feng-eric commented on services/database/program.ts
> +        //include: {},
Remove comment

2021-06-27 17:52 UTC, feng-eric requested changes
Had a few comments!

2021-06-28 01:01 UTC, jason17h commented on services/database/program.ts
> +async function getProgram(id: string) {
I think return type should be `Promise<Program>`

2021-06-28 06:38 UTC, feng-eric commented on pages/api/program/[id].ts
> +// TODO: Type the response data
This TODO still required?

2021-06-28 06:38 UTC, feng-eric commented on pages/api/program/[id].ts
> +        // obtain user with provided userId
```suggestion
        // obtain program with provided programId
```

2021-06-28 06:39 UTC, feng-eric commented on services/database/program.ts
> +
Add code documentation

2021-06-29 06:29 UTC, feng-eric commented
Hey @brandonwong368, I think you requested review but you didn't update the code.

2021-06-30 01:15 UTC, feng-eric commented on services/database/program.ts
> +
```suggestion
```

2021-06-30 01:19 UTC, feng-eric approved these changes
LGTM! Good work :)

2021-06-30 01:19 UTC, merged