add program sections table, attempt 2
uwblueprint/social-diversity-for-children pull request #23
Opened 2021-06-28 00:38 UTC by cindy-wang328

### Implementation description

Designers said each program should have different sections, with different days/times and age groups
![image](https://user-images.githubusercontent.com/50597354/123564196-62e9a180-d786-11eb-88a7-30331aeffabe.png)

### Steps to test

1. reset database on heroku website
2. heroku pg:psql -a sdc-dev-2 -f prisma/schema.sql
3. npx prisma introspect, npx prisma generate
4. change variable names in prisma file and add @@map 

### What should reviewers focus on?

- is there any info in the figma that is still missing
- maybe forgot some NOT NULL

2021-06-28 01:35 UTC, feng-eric requested changes
Had some comments!

2021-06-28 01:35 UTC, feng-eric commented on prisma/schema.prisma
> +  email              String            @unique
This should be removed from the parent table because we have it in the users table

2021-06-28 01:35 UTC, feng-eric commented on prisma/schema.sql
> +CREATE TYPE online_formats AS ENUM ('online', 'in-person', 'blended');
I think this should be called program_formats

2021-06-28 01:35 UTC, feng-eric commented on prisma/schema.sql
> +  email TEXT UNIQUE NOT NULL,
Let's remove this as it's in user table

2021-06-28 01:35 UTC, feng-eric commented on prisma/schema.sql
> -  FOREIGN KEY(id) REFERENCES users(id),
How come this was removed?

2021-06-28 01:35 UTC, feng-eric commented on prisma/schema.sql
> +  email TEXT UNIQUE,
Same as above

2021-06-28 01:35 UTC, feng-eric commented on prisma/schema.sql
> -  FOREIGN KEY(id) REFERENCES users(id),
Same as above

2021-06-29 06:42 UTC, feng-eric commented on prisma/schema.sql
> +CREATE TABLE sections (
We should have `ON DELETE CASCADE` so that if a program gets deleted, the associating records here also get deleted.

2021-06-29 06:42 UTC, feng-eric commented
@cindy-wang328 The designers came to the conclusion that they want to call it `classes` instead of `sections`. Could we make that change in this PR?

2021-06-30 01:38 UTC, cindy-wang328 commented
> @cindy-wang328 The designers came to the conclusion that they want to call it `classes` instead of `sections`. Could we make that change in this PR?

would there be any problems with confusing the OOP "class" with naming these models/tables "class"? like at work in the codebase theres some places that use "clazz" bc they cant use class as a variable name

2021-06-30 02:10 UTC, feng-eric commented on prisma/schema.prisma
> +  in_person @map("in-person")
there's actually a ticket to change all prisma fields to camelCase lol

2021-06-30 02:11 UTC, feng-eric commented on prisma/schema.prisma
> +  in_person @map("in-person")
you can ignore, we can do it in a separate PR

2021-06-30 02:11 UTC, feng-eric approved these changes
LGTM!

2021-06-30 02:12 UTC, merged

2021-06-30 02:12 UTC, feng-eric commented
This might break some stuff with the GET endpoint