Healthy Status Endpoint
uwblueprint/social-diversity-for-children pull request #5
Opened 2021-06-03 03:41 UTC by sohak22

Create A Status Endpoint
https://www.notion.so/uwblueprintexecs/Create-a-status-endpoint-eec29cc4976e48e2bfb010e50887d65d

We want to create a **/status** endpoint that returns information that the service is running. 

We want it to return 200 response code and the following message:

```json
{"status": "Healthy!"}

```

Steps to test

1. Run the application in local host : http://localhost:3000/api/status 
2. Page should return healthy status

2021-06-04 02:15 UTC, mahadzaryab1 requested changes
Added a couple of comments - some other things to consider:
- You can delete the /hello endpoint as it's replaced by this one 
- PR name should be imperative and descriptive. For example: **_Add Endpoint For Status Check_**

2021-06-04 02:15 UTC, mahadzaryab1 commented on pages/api/status.tsx
> +// Next.js API route support: https://nextjs.org/docs/api-routes/introduction
don't need this

2021-06-04 02:15 UTC, mahadzaryab1 commented on pages/api/status.tsx
> +export default (_req: NextApiRequest, res: NextApiResponse): void => {
add comment above function explaining what the function does

2021-06-04 02:43 UTC, feng-eric requested changes

2021-06-04 02:43 UTC, feng-eric commented on pages/api/status.tsx
> +// Next.js API route support: https://nextjs.org/docs/api-routes/introduction
I think you can remove this line

2021-06-05 04:18 UTC, feng-eric approved these changes
LGTM!

2021-06-05 15:20 UTC, mahadzaryab1 requested changes
I added some comments in my last review - could you take a look at those?

2021-06-06 15:15 UTC, mahadzaryab1 approved these changes
LGTM!

2021-06-06 17:27 UTC, merged