Add svg sdc logo and resize
uwblueprint/social-diversity-for-children pull request #66
Opened 2021-08-11 02:19 UTC by brandonwong368

### Notion ticket link

[Change PNG to SVG SDC Logo NavBar](https://www.notion.so/uwblueprintexecs/086c1b564dbf478faa649a8880e34b81?v=9d3f8002a0d1477ba395616dfc082af7&p=2c9a24bfaffc4930ab534942f92c79fe)

### Implementation description

- use the existing sdc logo blue svg file, add it to the navbar and resize 

### Steps to test

1.

### What should reviewers focus on?

-

### Checklist

-   [ ] My PR name is descriptive and in imperative tense
-   [ ] I have run the linter
-   [ ] I have requested a review from the PL, and/or other devs who have background knowledge on this PR or who will be building on top of this PR

2021-08-11 02:34 UTC, christinaruu commented
Looks amazing!!!

2021-08-11 02:35 UTC, christinaruu approved these changes

2021-08-11 19:40 UTC, feng-eric approved these changes
Great job!

2021-08-11 19:41 UTC, feng-eric requested changes
Wait, can you remove the `.DS_Store` and `public/.DS_Store` files?

2021-08-13 04:38 UTC, cindy-wang328 approved these changes

2021-08-13 04:40 UTC, feng-eric approved these changes

2021-08-13 04:41 UTC, merged