feature - empty state component for program/class views
uwblueprint/social-diversity-for-children pull request #81
Opened 2021-10-03 20:05 UTC by brandonwong368

### Notion ticket link

[Empty State Component for Program/Class Views](https://www.notion.so/uwblueprintexecs/086c1b564dbf478faa649a8880e34b81?v=9d3f8002a0d1477ba395616dfc082af7&p=5629a975400d4e5ca0bcc33eb4085c4f)

### Implementation description

- created an EmptyState component that styles and creates the grey box when there are no programs returned from the database
- the text will be wrapped by the component

![image](https://user-images.githubusercontent.com/71860803/135769736-7c79c8c4-4b57-4586-ab14-39433dca371b.png)

### Steps to test

1. Clear the database to make sure no programs are available, the index.tsx page route is the only page created so far with the empty state view

### What should reviewers focus on?

- does the empty state component show up when there are no programs
- do designs match the figma

### Checklist

-   [ ] My PR name is descriptive and in imperative tense
-   [ ] I have run the linter
-   [ ] I have requested a review from the PL, and/or other devs who have background knowledge on this PR or who will be building on top of this PR

2021-10-03 21:07 UTC, MatoPlus requested changes
Thanks for working on this Brandon! It was wayy over due. Just a couple of things noted below and I think we're all good.

If you can, please also add this to the `program-details/[id]` page. For example: https://social-diversity-for-children-pr-81.up.railway.app/en/program-details/2

2021-10-03 21:07 UTC, MatoPlus commented on pages/index.tsx
> +    const programCardInfos = [];
We probably undo this. Now that you did the testing. Next time, you could even do a `npx prisma studio` and delete the classes/programs in the database. Since they are seeded, you can get them back any time 😉

2021-10-03 21:07 UTC, MatoPlus commented on pages/index.tsx
> +                        <ProgramList cardInfo={programCardInfos} />
I still might want to consider the case where we are loading cards, maybe we want something like this instead?

```typescript
...
                    {programCardInfos.length === 0 ? (
                        <EmptyState>
                            {
                                "There are currently no programs available to register for.\nCome back shortly to see the programs we have to offer for the next term!"
                            }
                        </EmptyState>
                    ) : programCardInfos ? (
                        <ProgramList cardInfo={programCardInfos} />
                    ) : (
                        <Center>
                            <Spinner size="xl" />
                        </Center>
                    )}
....
```

2021-10-03 21:07 UTC, MatoPlus commented on src/components/EmptyState.tsx
> +        <Box bg={"#F8F8F8"} w="100%" py={"40px"} px={"64px"} color={"#737373"}>
I think we might want to add these colours into `src/styles/colours.ts` and use them from our colour palette. For example, look at how it is being used in the `volunteer-signup` page.
We might endup with the following:
```suggestion
        <Box bg={colourTheme.colors.Gray} w="100%" py={"40px"} px={"64px"} color={colourTheme.colors.LightGray}>
```

2021-10-03 23:19 UTC, bekahma reviewed
overall, it looks great! just some minor details from design:
1) overall margins of the page can be increased while decreasing the spacing between the text and image (see screenshot below)
2) make "Welcome to SDC" bigger than "Browse Programs" (should be 48px)

![image](https://user-images.githubusercontent.com/60044840/135775232-982417b0-a542-4be7-84af-ed31f3a97c86.png)

2021-10-04 02:49 UTC, MatoPlus commented
> some minor details from design:
> 
> 1. top margins between "Welcome to SDC" heading and secondary nav bar can be increased (see screenshot below)
> 2. make "Welcome to SDC" bigger than "Browse Programs" (should be 48px)
> 3. button styling is more rectangular to follow design systems
> 
> ![image](https://user-images.githubusercontent.com/60044840/135777716-ef8a22cc-5c87-4170-8696-9f09a457dff6.png)
> 
> looks great overall! :)

I definitely agree with these way overdue suggestions. @bekahma I'm guessing that mean there is no concern with the empty states?
![image](https://user-images.githubusercontent.com/44826218/135786077-46f15bce-2731-407c-bb39-c1a6942e8ba7.png)

@brandonwong368 please make the suggested changes if possible, otherwise we make another ticket to address these issues with the home page.

2021-10-04 14:44 UTC, bekahma commented
> > some minor details from design:
> > 
> > 1. top margins between "Welcome to SDC" heading and secondary nav bar can be increased (see screenshot below)
> > 2. make "Welcome to SDC" bigger than "Browse Programs" (should be 48px)
> > 3. button styling is more rectangular to follow design systems
> > 
> > ![image](https://user-images.githubusercontent.com/60044840/135777716-ef8a22cc-5c87-4170-8696-9f09a457dff6.png)
> > looks great overall! :)
> 
> I definitely agree with these way overdue suggestions. @bekahma I'm guessing that mean there is no concern with the actual empty states? ![image](https://user-images.githubusercontent.com/44826218/135786077-46f15bce-2731-407c-bb39-c1a6942e8ba7.png)
> 
> @brandonwong368 please make the suggested changes if possible 🙏 , otherwise we can make another ticket to address these issues with the home page.

yes no issues with the empty state! my bad for not reading the notion ticket before commenting - just went purely off of railway + screenshot

2021-10-10 02:29 UTC, MatoPlus approved these changes
LGTM

2021-10-10 02:30 UTC, merged