[WIP] My Accounts Page
uwblueprint/social-diversity-for-children pull request #85
Opened 2021-10-04 12:44 UTC by GodGreg

### Notion ticket link

[Ticket Name](https://www.notion.so/uwblueprintexecs/086c1b564dbf478faa649a8880e34b81?v=9d3f8002a0d1477ba395616dfc082af7)

### Implementation description

-

### Steps to test

1.

### What should reviewers focus on?

-

### Checklist

-   [ ] My PR name is descriptive and in imperative tense
-   [ ] I have run the linter
-   [ ] I have requested a review from the PL, and/or other devs who have background knowledge on this PR or who will be building on top of this PR

2021-10-04 13:17 UTC, MatoPlus commented
I know this is a draft but took a quick peek, please try to use the Text component for <text> and Box component for <div>, we want to stick with chakra counterparts as much as possible.

2021-10-04 13:27 UTC, GodGreg commented
> I know this is a draft but took a quick peek, please try to use the Text component for and Box component for
> 
> , we want to stick with chakra counterparts as much as possible.

Sure thing!

2021-10-26 04:48 UTC, MatoPlus requested changes
Some nitpicks basically just mostly replacing icons and adding 1 more missing field in our forms.

2021-10-26 04:48 UTC, MatoPlus commented on pages/myaccounts.tsx
> +                    icon: MdAccountCircle,
This icon matches the design:
```suggestion
                    icon: MdPerson,
```

2021-10-26 04:48 UTC, MatoPlus commented on pages/myaccounts.tsx
> +                icon: MdPersonOutline,
better icon for design
```suggestion
                icon: MdSupervisorAccount,
```

2021-10-26 04:48 UTC, MatoPlus commented on pages/myaccounts.tsx
> +                icon: MdArticle,
```suggestion
                icon: MdDescription,
```

2021-10-26 04:48 UTC, MatoPlus commented on src/components/formFields/CheckBoxField.tsx
> +                    disabled={!edit}
Checkboxes are a bit weird, instead of `disabled` we want to use `isDisabled` instead as per the docs
```suggestion
                    isDisabled={!edit}
```

2021-10-26 04:48 UTC, MatoPlus commented on src/components/myAccounts/ParticipantInformation.tsx
> +    const [expectations, setExpections] = useState();
```suggestion
    const [expectations, setExpections] = useState(
        props.student.guardianExpectations,
    );
```

2021-10-26 04:48 UTC, MatoPlus commented on src/components/myAccounts/ParticipantInformation.tsx
> +                        spacing={false}
```suggestion
                        spacing={false}
                        edit={props.edit}
```

2021-10-26 04:48 UTC, MatoPlus commented on src/components/myAccounts/ParticipantInformation.tsx
> +                        spacing={false}
```suggestion
                        spacing={false}
                        edit={props.edit}
```

2021-10-26 04:48 UTC, MatoPlus commented on src/components/myAccounts/ParticipantInformation.tsx
> +                        spacing={false}
```suggestion
                        spacing={false}
                        edit={props.edit}
```

2021-10-26 04:48 UTC, MatoPlus commented on src/components/myAccounts/ParticipantInformation.tsx
> +                        spacing={false}
```suggestion
                        spacing={false}
                        edit={props.edit}
```

2021-10-26 04:48 UTC, MatoPlus commented on src/components/myAccounts/ParticipantInformation.tsx
> +                        spacing={false}
```suggestion
                        spacing={false}
                        edit={props.edit}
```

2021-10-26 04:48 UTC, MatoPlus commented on src/components/myAccounts/ParticipantInformation.tsx
> +                        spacing={false}
```suggestion
                        spacing={false}
                        edit={props.edit}
```

2021-10-26 04:48 UTC, MatoPlus commented on src/components/myAccounts/ParticipantInformation.tsx
> +                        spacing={false}
```suggestion
                        spacing={false}
                        edit={props.edit}
```

2021-10-26 04:48 UTC, MatoPlus commented on src/components/myAccounts/ParticipantInformation.tsx
> +                        spacing={false}
```suggestion
                        spacing={false}
                        edit={props.edit}
```

2021-10-26 04:48 UTC, MatoPlus commented on src/components/myAccounts/ParticipantInformation.tsx
> +                        spacing={false}
```suggestion
                        spacing={false}
                        edit={props.edit}
```

2021-10-26 04:48 UTC, MatoPlus commented on src/components/myAccounts/ParticipantInformation.tsx
> +                        spacing={false}
```suggestion
                        spacing={false}
                        edit={props.edit}
```

2021-10-26 04:48 UTC, MatoPlus commented on src/components/myAccounts/ParticipantInformation.tsx
> +                <br />
Add missing TextField in design for expectations.
```suggestion
                <TextField
                    name="Parent/Guardian Expectations"
                    value={expectations}
                    setValue={setExpections}
                    edit={props.edit}
                ></TextField>
                <br />
                <br />
```

2021-10-26 04:48 UTC, MatoPlus commented on src/components/myAccounts/ParticipantInformation.tsx
> +                        setValue={setEmergFirstName}
```suggestion
                        setValue={setEmergFirstName}
                        edit={props.edit}
```

2021-10-26 04:48 UTC, MatoPlus commented on src/components/myAccounts/ParticipantInformation.tsx
> +                        setValue={setEmergLastName}
```suggestion
                        setValue={setEmergLastName}
                        edit={props.edit}
```

2021-10-26 04:48 UTC, MatoPlus commented on src/components/myAccounts/ParticipantInformation.tsx
> +                    setValue={setEmergPhoneNumber}
```suggestion
                    setValue={setEmergPhoneNumber}
                    edit={props.edit}
```

2021-10-26 04:48 UTC, MatoPlus commented on src/components/myAccounts/ParticipantInformation.tsx
> +                    setValue={setEmergRelationship}
```suggestion
                    setValue={setEmergRelationship}
                    edit={props.edit}
```

2021-10-26 04:48 UTC, MatoPlus commented on src/components/myAccounts/ParticipantInformation.tsx
> +                    required={false}
```suggestion
                    required={false}
                    edit={props.edit}
```

2021-10-26 04:48 UTC, MatoPlus commented on src/components/myAccounts/ParticipantInformation.tsx
> +                    required={false}
```suggestion
                    required={false}
                    edit={props.edit}
```

2021-10-26 04:48 UTC, MatoPlus commented on pages/myaccounts.tsx
> +                icon: MdPersonOutline,
```suggestion
                icon: MdPerson,
```

2021-10-26 04:48 UTC, MatoPlus commented on pages/myaccounts.tsx
> +                icon: MdArticle,
```suggestion
                icon: MdDescription,
```

2021-10-26 16:37 UTC, MatoPlus commented on utils/validation/fields.ts
> +export function testPhoneNumber(phonenumber: string) {
Not used

2021-10-26 16:37 UTC, MatoPlus commented on src/components/volunteer-form/VolunteerDetailsPage.tsx
> +import { testCanadianPostalCode } from "@utils/validation/fields";
not used

2021-10-26 16:37 UTC, MatoPlus approved these changes
LGTM! Thanks for getting this in!

2021-10-26 16:38 UTC, merged